import { Inter, Epilogue, Mohave } from "next/font/google";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import WhatsAppButton from "./components/Whatsapp";
import "./globals.css";

const inter = Inter({
  variable: "--font-secondary",
  subsets: ["latin"],
});

const epilogue = Epilogue({
  variable: "--font-primary",
  subsets: ["latin"],
});

const mohave = Mohave({
  variable: "--font-tertiary",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${epilogue.variable} ${mohave.variable} h-full antialiased`}
    >
      <body>
        <Navbar />
        <main className="min-h-full flex flex-col">
          <WhatsAppButton
            phoneNumber="+971501234567"
            message="Hi! I'd like to request a quote."
          />
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
